apps/dcor/urls.py
# HiPerCic Project / St. Olaf College / Computer Science Dept.
###################################################################################
# apps/dcor/urls.py
# Holds url patterns for the app site.  Links urls requested by users to various view functions
###################################################################################
from django.conf.urls.defaults import *

urlpatterns = patterns(
    # The path to this specific app's view functions
    'hipercic.apps.dcor.views', # remember to insert your app's name!
    (r'^$', 'home'),  # calls the home view!
	(r'^jobs/$', 'job_submit'),
	(r'^jobs/submit', 'job_submit'),
	(r'^jobs/two_assets', 'job_two_assets'),
	(r'^jobs/multi_assets', 'job_multi_assets'),
	(r'^jobs/result', 'job_result'),
    (r'^about/$', 'about_us'),
    (r'^about/project', 'about_project'),
    (r'^about/glossary$', 'glossary'),
    (r'^about/etf_explanations$', 'etf_explanations'),
)

hipercore/urls.py
# HiPerCic Project / St. Olaf College / Computer Science Dept.
###################################################################################
# hipercic/urls.py
# Created 6/11
# Base URLs document for hipercic project
###################################################################################
from django.conf.urls.defaults import *
from hipercic.hipercore import admin

#admin.autodiscover()
from hipercic.hipercore.authenticore.views import login, logout
from hipercic.hipercore.admin.views.hipercic_home import placeHolder
from hipercic.apps.appConfig import *

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^hipercic/', include('hipercic.foo.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

   #(r'^accounts/logout/$', logout),
    
    # site header (cjc 6/9)
    (r'^$', admin.site.login), 
    
    # this page should be removed or developed further...
    (r'^placeHolder/$', placeHolder),
    
    # documentation subsite
    #(r'^docs/', include('hipercic.hipercore.documentation.urls')),


    # for the bugreporter subsite
    #(r'^bugs/', include('hipercic.hipercore.bugs.urls')),
	
    # for the local API
    #(r'^api/', include('hipercic.hipercore.apiUrls')),

    # for the epyapi
    #(r'^epy_api/', include('hipercic.hipercore.epyUrls')),

)

### append the urlpatterns for the installed apps
urlpatterns += getAppURLPatterns()

apps/dcor/models.py
# HiPerCic Project / St. Olaf College / Computer Science Dept.
###################################################################################
# apps/dcor/models.py
# Created INSERT_DATE
# Holds "models", which are Django classes that are synced to the database.
###################################################################################
from django.db import models

### Create your models here. ###
### Each model is a class, extending models.Model
### For help with models, check out https://docs.djangoproject.com/en/dev/topics/db/models/
### Once you have set up your models, be sure to run 'hipercic-local/manage syncdb --database=DB_NAME' in your hipercic top directory.  This will configure the database for you.
### Note that models cannot be linked to models in other databases using ForeignKey relationships.  You'll have to do that lookup manually.
class Asset(models.Model):
	name = models.CharField("asset name", max_length=100)

class Record(models.Model):
	asset		 = models.ForeignKey(Asset, on_delete=models.PROTECT)
	date         = models.DateField("record date")
	closed_price = models.DecimalField(max_digits=10, decimal_places=2)

apps/dcor/views.py
# HiPerCic Project / St. Olaf College / Computer Science Dept.
###################################################################################
# apps/dcor/views.py
# Holds the methods which render templates into pages.  Called from urls.py
###################################################################################
import subprocess
import os

from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import Template, Context
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.core import serializers
from django.views.decorators.csrf import *
from django import forms
from django.forms.widgets import CheckboxSelectMultiple
from django.db import models

from datetime import datetime
from os.path import expanduser
from hipercic.apps.dcor import models # Don't forget to dcor!!!
from hipercic.hipercore.admin.hipercicViewHelpers import NavigationBar
from hipercic.hipercore.authenticore.decorators import login_required

BACKEND_SERVER_LOCATION = 'guillet@helios.public.stolaf.edu'
BACKEND_FOLDER_NAME     = 'dcor_backend'
CURRENT_HOME_FOLDER     =  expanduser('~')

ASSET_CHOICES = []
for a in models.Asset.objects.raw('SELECT * FROM dcor_asset'):
	temp_tuple = (str(a.name), str(a.name))
	ASSET_CHOICES.append(temp_tuple)
	
class TwoAssetsForm(forms.Form):
	start_date = forms.DateField()
	end_date   = forms.DateField()
	asset1     = forms.ChoiceField(ASSET_CHOICES)
	per_asset1 = forms.IntegerField(min_value = 0, max_value = 100)
	asset2     = forms.ChoiceField(ASSET_CHOICES)
	per_asset2 = forms.IntegerField(min_value = 0, max_value = 100)

class MultiAssetsForm(forms.Form):
	start_date       = forms.DateField()
	end_date         = forms.DateField()
	assets           = forms.MultipleChoiceField(required=True, widget=CheckboxSelectMultiple, choices=ASSET_CHOICES)
	portfolio_size  = forms.IntegerField()

# include csrf protection and standard Hipercic title block
#@login_required    # uncomment to require a login -- for use on a full server only!

def home(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'Home'
	context.update(csrf(request))  # add cross-site request forgery protection - useful for POST and javascript
	context.update({'csrfTokenValue':csrf(request)['csrf_token']})  # add the token a second way
	return render_to_response('base_home.html', context)
 

def job_submit(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'Submit'
	context.update(csrf(request))  # add cross-site request forgery protection - useful for POST and javascript
	context.update({'csrfTokenValue':csrf(request)['csrf_token']})  # add the token a second way
	return render(request, 'base_job_submit.html', context)

def job_two_assets(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'Two Assets Job'
	context.update(csrf(request))  # add cross-site request forgery protection - useful for POST and javascript
	context.update({'csrfTokenValue':csrf(request)['csrf_token']})  # add the token a second way
		
	form = TwoAssetsForm(request.POST or None)
	context['form'] = form
	if request.method == 'POST':
		if form.is_valid():
			# write file in ~/hipercic/apps/dcor/jobs/
			with open('apps/dcor/jobs/job_' + datetime.today().strftime("%Y%m%d_%H%M%S") + '_params.txt', 'w') as params_file:
				params_file.write(str(form.cleaned_data['start_date']) + '\n')
				params_file.write(str(form.cleaned_data['end_date']) + '\n')
				params_file.write(str(form.cleaned_data['asset1']) + ',')
				params_file.write(str(form.cleaned_data['asset2']) + '\n')
				params_file.write(str(form.cleaned_data['per_asset1']) + ',')
				params_file.write(str(form.cleaned_data['per_asset2']) + '\n')
				params_file.write(str(2)) # default value for portofolio_size

			request.session['job_filename'] = params_file.name
			scp = 'scp ' + CURRENT_HOME_FOLDER + '/hipercic/' + params_file.name + ' ' + BACKEND_SERVER_LOCATION + ':' + BACKEND_FOLDER_NAME + '/jobs/'
			return_code_scp = subprocess.call(scp, shell=True)
		
			head, tail = os.path.split(params_file.name)
			cpp = 'ssh ' + BACKEND_SERVER_LOCATION + ' "cd ' + BACKEND_FOLDER_NAME + '; ./dcor jobs/' + tail + '"'
			return_code_cpp = subprocess.call(cpp, shell=True)
			return render(request, 'base_job_result.html', context)

	return render(request, 'base_job_two_assets.html', context)

def job_multi_assets(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'Multi Assets Job'
	context.update(csrf(request))  # add cross-site request forgery protection - useful for POST and javascript
	context.update({'csrfTokenValue':csrf(request)['csrf_token']})  # add the token a second way
	
	form = MultiAssetsForm(request.POST or None)
	context['form'] = form
	if request.method == 'POST':
		if form.is_valid():
			# write file in ~/hipercic/apps/dcor/jobs/
			with open('apps/dcor/jobs/job_' + datetime.today().strftime("%Y%m%d_%H%M%S") + '_params.txt', 'w') as params_file:
				params_file.write(str(form.cleaned_data['start_date']) + '\n')
				params_file.write(str(form.cleaned_data['end_date']) + '\n')
				params_file.write(u','.join(form.cleaned_data['assets']) + '\n')
				# only for consistency of file format between two and multi assets mode	
				params_file.write('void\n')
				params_file.write(str(form.cleaned_data['portfolio_size']))
			
			request.session['job_filename'] = params_file.name
			scp = 'scp ' + CURRENT_HOME_FOLDER + '/hipercic/' + params_file.name + ' ' + BACKEND_SERVER_LOCATION + ':' + BACKEND_FOLDER_NAME + '/jobs/'
			return_code_scp = subprocess.call(scp, shell=True)
		
			head, tail = os.path.split(params_file.name)
			cpp = 'ssh ' + BACKEND_SERVER_LOCATION + ' "cd ' + BACKEND_FOLDER_NAME + '; ./dcor jobs/' + tail + '"'
			return_code_cpp = subprocess.call(cpp, shell=True)
			return render(request, 'base_job_result.html', context)	
	
	return render(request, 'base_job_multi_assets.html', context)

def job_result(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'Job result'
	context.update(csrf(request))  # add cross-site request forgery protection - useful for POST and javascript
	context.update({'csrfTokenValue':csrf(request)['csrf_token']})  # add the token a second way

	job_filename = request.session['job_filename']
	with open(job_filename, 'r') as job_parameters_file:
		for line_number, line in enumerate(job_parameters_file):
			if line_number == 0:
				context['param_start_date'] = line.rstrip()
			if line_number == 1:
				context['param_stop_date'] = line.rstrip()
			if line_number == 2:
				context['param_assets'] = line.rstrip()
			if line_number == 3:
				context['param_percentages'] = line.rstrip()

	two_assets_mode = False
	if context['param_percentages'] != 'void':
		two_assets_mode = True
		
	if (two_assets_mode):
		context['two_assets_mode'] = 'true' 
	else:
		context['two_assets_mode'] = 'false' 

	job_result_filename = job_filename[:-4] + '_results.txt'
	context['job_result_filename'] = job_result_filename	
	with open(job_result_filename, 'r') as job_result_file:
		for line_number, line in enumerate(job_result_file):
			if line_number == 0:
				context['return_value'] = line.rstrip()
			if line_number == 1:
				context['result_start_date'] = line.rstrip()
			if line_number == 2:
				context['result_stop_date'] = line.rstrip()
			if line_number == 3:
				context['result_combination'] = line.rstrip()
			if line_number == 4:
				context['result_percentages'] = line.rstrip()
			if line_number == 5:
				context['portfolio_distribution'] = '[' + line.rstrip() + ']'
	return render_to_response('base_job_result.html', context)

def about_us(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'About Us'
	return render_to_response('base_about_us.html', context)


def about_project(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'About Project'
	return render_to_response('base_about_project.html', context)

def glossary(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'Glossary'
	return render_to_response('base_glossary.html', context)

def etf_explanations(request):
	navbar = NavigationBar()
	context = navbar.generateNavBar(request, current_app='dcor')
	context['title'] = 'ETF Explanations'
	return render_to_response('base_etf_explanations.html', context)

apps/dcor/templates/base.html
{% extends "admin/base_site.html" %}
{% block content %}
<style type="text/css">
#header {
background: #608894;
border-bottom: solid 1px black;
border-top: solid 1px black;
}

#navbar {
	display: none;
}

#branding img {
	height: 90px;
	width: 160px;
}

body {
	font-size: 14px;
	background-color: #E0E0E0;
}

ul, li {
	font-size: 14px;
}

th {
	font-size: 16px;
}

#sddm {
margin-left: 215px;
padding: 0;
z-index: 30;
}


#sddm li {
padding: 0;
margin-bottom: 40px;
list-style: none;
float: left;
font: bold 14px arial;
}

#sddm li a {
border-bottom: solid 1px black;
border-left: solid 1px black;
border-top: solid 1px #6088894;
display: block;
margin: 0 0 0 0;
padding: 4px 10px;
width: 100px;
height: 14px;
background: #608894;
color: black;
text-align: center;
text-decoration: none;
}

#sddm li a:hover {
background: #DB9F63;
}

#sddm #home {
}

#sddm #about {
border-right: solid 1px black;
}

#sddm div {
position: absolute;
visibility: hidden;
width: 140px;
margin: 0;
padding: 0;
background: #EAEBD8;
border: 1px solid #417690;
z-index: 56;
}

#sddm div a {
position: relative;
display: block;
margin: 0;
padding: 5px 10px;
width: auto;
white-space: nowrap;
text-align: left;
text-decoration: none;
background: #EAEBD8;
color: #2875DE;
font: 12px arial;
}

#sddm div a:hover {
background: #49A3FF;
color: #FFF;
}
</style>

<script language="javascript">
var timeout = 250;
var closetimer = 0;
var ddmenuitem = 0;

function mopen(id){
  mcancelclosetime();
  if(ddmenuitem) ddmenuitem.style.visibility = 'hidden';
  ddmenuitem = document.getElementById(id);
  ddmenuitem.style.visibility = 'visible';
}

function mclose(){
  if(ddmenuitem) ddmenuitem.style.visibility = 'hidden';
}

function mclosetime(){
  closetimer = window.setTimeout(mclose, timeout);
}

function mcancelclosetime(){
  if(closetimer)
  {
    window.clearTimeout(closetimer);
    closetimer = null;
  }
}

document.onclick = mclose;
</script>

<ul id="sddm">
  <li id="home"><a href="/dcor">Home</a>
  </li>
  <li><a href="/dcor/jobs/submit"
	 onmouseover="mopen('m1')"
	 onmouseout="mclosetime()">Jobs</a>
    <div id="m1"
	 onmouseover="mcancelclosetime()"
	 onmouseout="mclosetime()">
      <a href="/dcor/jobs/submit">Submit a Job</a>
      <a href="/dcor/jobs/result">Last Completed Job</a>
    </div>
  </li>
  <li id="about"><a href="/dcor/about/"
	 onmouseover="mopen('m2')"
	 onmouseout="mclosetime()">About</a>
    <div id="m2"
	 onmouseover="mcancelclosetime()"
	 onmouseout="mclosetime()">
      <a href="/dcor/about/project">Project</a>
      <a href="/dcor/about/glossary">Glossary</a>
      <a href="/dcor/about/etf_explanations">ETF's</a>
    </div>
  </li>
</ul>
<div style="clear:both"></div>
{% block center-col %}{% endblock %}	
{% endblock %}

apps/dcor/templates/base_about.html
{% extends "base.html" %}
{% block center-col %}
<h1>Explanation of “Downside Correlation of Investment Asset Classes”</h1> 

<h2>Origin/Goals</h2> 
D-Cor is a HiPerCiC (High-performance computing in the classroom) application designed to determine the optimal combination of asset classes in a portfolio during a downturn in the economy. Investors and financial market researchers do not examine correlation meticulously when the markets are good and the economy is booming. However, when security prices have been falling for a while, average investors and fund managers alike start asking the question, “What should I be investing in to avoid the worst of this crisis?” The answer to that question is what Professor Rick Goedde’s research and the D-Cor application attempt to discover. Domain Professor Goedde brought his research idea to the HiPerCiC course, and a team of two implementation students, Benjamin Guillet and Ian Zewiske, and one domain student, Ryan Johnsrud, collaborated to develop the D-Cor app. 
<br />

<h2>ETFs</h2> 
For asset classes, this application uses Exchange Traded Funds, or ETFs, which give investors a stake in pools of related securities. An ETF is an investment fund that holds assets such as stocks, commodities, or bonds. Most ETFs track a stock or bond index, which is a statistical measure of changes in a representative group of individual stock or bond prices. Exchange Traded Funds are similar in many ways to mutual funds, but are traded throughout the whole trading day on various international stock exchanges. For a list of ETFs used in D-Cor and an explanation of each, click here.***LINK***
<br /> 

<h3>Different Financial Services companies offer Exchange Traded Funds. In this project we used ETFs from:</h3>
BlackRock iShares - http://us.ishares.com/home.htm <br />
Vanguard - https://investor.vanguard.com/home/<br />
Charles Schwab - https://www.schwab.com/ <br />
SPDR by State Street Global Advisors - https://www.spdrs.com/index.seam <br />
Dimensional Fund Advisors - http://www.dfaus.com/ <br />
Invesco PowerShares http://www.invescopowershares.com/ <br />

<h2>How It Works</h2>
First, the user inputs various parameters, including:
start and end dates, 
number of asset classes in the portfolio, 
which asset classes (ETFs) to exclude, and
portion of total portfolio value invested in each ETF.
Then, the computer program tests each combination of asset classes (that the user has indirectly selected through the chosen parameters) for their worst period of returns within the allotted start and end dates. The computer finds each period where the world’s worst investor purchased this combination of ETFs at the highest price within the pre-selected time period, and proceeded to sell at the lowest point. Once a “worst return” is calculated for each combination, D-Cor tells the user what combination would be the best of the worst. Finally, this winning combination of asset classes—the portfolio which would have lost the investor the least amount of money during this time period—is displayed on the results page.

{% endblock %}

apps/dcor/templates/base_about_us.html
{% extends "base.html" %}
{% block center-col %}
<style type="text/css">

#about_us {
border: solid 1px black;
margin: 25px 0 0 50px;
width: 900px;
}

#about_us td {
background: white;
padding: 10px;
border: 1px solid black;
}

#about_us span {
font-weight: bold;
font-size: 14px;
}

#title {
color: black;
}

#about_us th {
background: #DB9F63;
border: solid 1px black;
}

</style>
<table id="about_us">
  <tbody>
    <tr>
      <th><span id="title">About</span></th>
    </tr>
    <tr>
      <td>This application was built by Benjamin Guillet, Ryan Johnsrud and Ian Zewiske, members of the Integrative Studies (IS) 201 course at St. Olaf College, taught by Dr. Richard Brown, Spring 2013. The idea was proposed by Professor Richard Goedde.</td>
    </tr>
     </tbody>
</table>
{% endblock %}

apps/dcor/templates/base_glossary.html
{% extends "base.html" %}
{% block center-col %}
<style type="text/css">

#glossary {
border: solid 1px black;
margin: 25px 0 0 50px;
}

#glossary td {
background: white;
padding: 10px;
border: 1px solid black;
}

#glossary span {
font-weight: bold;
font-size: 14px;
}

#title {
color: black;
}

#glossary th {
background: #DB9F63;
border: solid 1px black;
}

</style>
<table id="glossary">
  <tbody>
    <tr>
      <th><span id="title">Glossary</span></th>
    </tr>
    <tr>
      <td>
	<span id="MarCap">Market Capitalization:</span> The total value of issued shares of a publicly traded company. Equal to the current share price multiplied by the<br>number of shares outstanding. This represents the public consensus on the value of a company's equity.
      </td>
    </tr>
    <tr>
      <td>
	<span id="LarCap">Large-cap (capitalization):</span> Short for 'large companies' with Market Capitalization > $10 billion.
      </td>
    </tr>
    <tr>
      <td>
	<span id="MidCap">Mid-cap:</span> Medium-sized companies; Capitalization between $2 and $10 billion.
      </td>
    </tr>
    <tr>
      <td id="bot">
	<span id="SmaCap">Small-cap:</span> Small companies between $250 million and $2 billion Capitalization.
      </td>
    </tr>
  </tbody>
</table>
{% endblock %}

apps/dcor/templates/base_job_multi_assets.html
{% extends "base.html" %}
{% block extrahead %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
	<link rel="stylesheet" href="/static/css/jquery.fancybox.css" />
{% endblock %}
{% block center-col %}
	{% if form.errors %}
		<p>This field contains errors:</p>
		{% for error in form.errors %}
			{{ error }}
		{% endfor %}
	{% endif %}
	<form id="multi_assets" action="multi_assets" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>
	{% endblock %}
{% block custom_scripts %}
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
	<script src="/static/js/jquery.fancybox.pack.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			"use strict";
		
			var id_start_date = $('#id_start_date'); 
			var id_end_date  = $('#id_end_date'); 
			var id_portfolio_size = $('#id_portfolio_size');
			id_start_date.datepicker();
			id_end_date.datepicker();
			
			var idPerAsset1 = $('#id_per_asset1');
			var idPerAsset2 = $('#id_per_asset2');
			idPerAsset1.keyup(function () {
				var per1 = $(this).val();
				idPerAsset2.val(100 - per1);
			});
			
			idPerAsset2.keyup(function () {
				var per2 = $(this).val();
				idPerAsset1.val(100 - per2);
			});
		
			$('#multi_assets').submit(function() {
				if (id_start_date.val() === '') {
					alert('Please enter a start date');
					return false;
				}

				if (id_end_date.val() === '') {
					alert('Please enter a end date');
					return false;
				}

				var number_checked = $('input:checked').length;  

				if (number_checked < 2) {
					alert('Please check at least 2 checkboxes');
					return false;
				}
	
				if (id_portfolio_size.val() === '') {
					alert('Please enter a portfolio size');
					return false;
				}

				if (id_portfolio_size.val() > number_checked) {
					alert('You must chose a portfolio size smaller or equal to the number of chosen checkboxes');
					return false;
				}



				$.ajax({
					data: $(this).serialize(), // get the form data
					type: $(this).attr('method'), // GET or POST
					url: $(this).attr('action'), // the file to call
					beforeSend: function() {
						$.fancybox.open({
							href : '/static/img/ajax_loader.gif',
							title: 'Please wait.'
						});
					},
					complete: function() {
						window.location.replace('/dcor/jobs/result');
					}
				});
				return false;
			});
	
		});
	</script>
{% endblock %}

apps/dcor/templates/base_job_submit.html
{% extends "base.html" %}
{% block extrahead %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
{% endblock %}
{% block center-col %}
	<ul>
		<li><a href="two_assets">Two assets portfolio</a></li>
		<li><a href="multi_assets">Multi assets portfolio</a></li>
	</ul>
	{% endblock %}
{% block custom_scripts %}
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			"use strict";
			
			$('#id_start_date').datepicker();
			$('#id_end_date').datepicker();
			
			var idPerAsset1 = $('#id_per_asset1');
			var idPerAsset2 = $('#id_per_asset2');
			idPerAsset1.keyup(function () {
				var per1 = $(this).val();
				idPerAsset2.val(100 - per1);
			});
			
			idPerAsset2.keyup(function () {
				var per2 = $(this).val();
				idPerAsset1.val(100 - per2);
			});
		
		});
	</script>
{% endblock %}

apps/dcor/templates/base_job_two_assets.html
{% extends "base.html" %}
{% block extrahead %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
	<link rel="stylesheet" href="/static/css/jquery.fancybox.css" />
{% endblock %}
{% block center-col %}
	{% if form.errors %}
		<p>This field contains errors:</p>
		{% for error in form.errors %}
			{{ error }}
		{% endfor %}
	{% endif %}
	<form id="two_assets" action="two_assets" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>
{% endblock %}
{% block custom_scripts %}
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
	<script src="/static/js/jquery.fancybox.pack.js"></script>
    
	<script type="text/javascript">
		$(document).ready(function () {
			"use strict";
			
			var id_start_date = $('#id_start_date');
			var id_stop_date = $('#id_end_date');
			var id_per_asset1 = $('#id_per_asset1');		
			var id_per_asset2 = $('#id_per_asset2');
			var id_asset1 = $('#id_asset1');
			var id_asset2 = $('#id_asset2');

			id_start_date.datepicker();
			id_stop_date.datepicker();
			
			var idPerAsset1 = $('#id_per_asset1');
			var idPerAsset2 = $('#id_per_asset2');
			idPerAsset1.keyup(function () {
				var per1 = $(this).val();
				idPerAsset2.val(100 - per1);
			});
			
			idPerAsset2.keyup(function () {
				var per2 = $(this).val();
				idPerAsset1.val(100 - per2);
			});
		
			$('#two_assets').submit(function() {
				
				if (id_start_date.val() === '') {
					alert('Please enter a start date');
					return false;
				}
				
				if (id_stop_date.val() === '') {
					alert('Please enter a stop date');
					return false;
				}

				if (id_per_asset1.val() === '') {
					alert('Please enter a percentage for asset 1');
					return false;
				}

				if (id_per_asset2.val() === '') {
					alert('Please enter a percentage for asset 2');
					return false;
				}

				if (id_asset1.val() === id_asset2.val()) {
					alert('You must chose two different assets');
					return false;
				}

				$.ajax({ 
					data: $(this).serialize(), // get the form data
					type: $(this).attr('method'), // GET or POST
					url: $(this).attr('action'), // the file to call
					beforeSend: function() {
						$.fancybox.open({
							href : '/static/img/ajax_loader.gif',
							title: 'Please wait.'
						});
					},
					complete: function() {
						window.location.replace('/dcor/jobs/result');
					}
				});
				return false;
			});
		});
	</script>
{% endblock %}

apps/dcor/templates/base_pending.html
{% extends "base.html" %}
{% block extrahead %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
{% endblock %}
{% block center-col %}
<p>Success! Job is pending!</p>
<p>Command sent: {{ cmd }}</p>
{% endblock %}

apps/dcor/templates/base_submit.html
{% extends "base.html" %}
{% block extrahead %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
{% endblock %}
{% block center-col %}
	{% if form.errors %}
		<p>This field contains errors:</p>
		{% for error in form.errors %}
			{{ error }}
		{% endfor %}
	{% endif %}
	<form action="submit" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>
	{% endblock %}
{% block custom_scripts %}
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			"use strict";
			
			$('#id_start_date').datepicker();
			$('#id_end_date').datepicker();
			
			var idPerAsset1 = $('#id_per_asset1');
			var idPerAsset2 = $('#id_per_asset2');
			idPerAsset1.keyup(function () {
				var per1 = $(this).val();
				idPerAsset2.val(100 - per1);
			});
			
			idPerAsset2.keyup(function () {
				var per2 = $(this).val();
				idPerAsset1.val(100 - per2);
			});
		
		});
	</script>
{% endblock %}